apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemoapp-deployment
  namespace: Kube-system
  labels:
    app: dotnetdemoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetdemoapp
  template:
    metadata:
      labels:
        app: dotnetdemoapp
    spec:
      containers:
        - name: dotnetdemoapp
          image: raznerdeveloper/dotnetshopdemo
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development