---
apiVersion: v1
kind: Service
metadata:
  name: dotnetdemoapp
  namespace: default
  labels:
    app: dotnetdemoapp
spec:
  selector:
    app: dotnetdemoapp
  ports:
    - port: 80
      name: http
      targetPort: http